/**
 * PatientAlertsBanner - Real-time Patient Safety Alerts
 *
 * StudioVision Parity: Visual alert banner for critical patient info
 *
 * Features:
 * - Allergies with severity indicators
 * - Overdue follow-up reminders
 * - Pending lab results alerts
 * - Medication reminders
 * - Custom alerts
 * - Dismissible and acknowledgeable alerts
 * - Priority-based ordering
 *
 * Usage:
 * <PatientAlertsBanner
 *   patientId={patient._id}
 *   alerts={patient.patientAlerts}
 *   allergies={patient.allergies}
 *   compact={false}
 * />
 */

import { useState, useCallback, useMemo } from 'react';
import {
  AlertCircle,
  AlertTriangle,
  Info,
  CheckCircle,
  X,
  ChevronDown,
  ChevronUp,
  Clock,
  Activity,
  Bell,
  Eye,
  MoreVertical
} from 'lucide-react';
import { toast } from 'react-toastify';

// Alert type configuration
const ALERT_TYPES = {
  allergy: {
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
    textColor: 'text-red-700',
    badgeColor: 'bg-red-100 text-red-800',
    icon: AlertCircle,
    label: 'Allergie',
    priority: 100,
    canDismiss: false
  },
  urgent: {
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
    textColor: 'text-red-700',
    badgeColor: 'bg-red-100 text-red-800',
    icon: AlertCircle,
    label: 'Urgent',
    priority: 90,
    canDismiss: true
  },
  warning: {
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
    textColor: 'text-orange-700',
    badgeColor: 'bg-orange-100 text-orange-800',
    icon: AlertTriangle,
    label: 'Attention',
    priority: 70,
    canDismiss: true
  },
  reminder: {
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-300',
    textColor: 'text-yellow-700',
    badgeColor: 'bg-yellow-100 text-yellow-800',
    icon: Clock,
    label: 'Rappel',
    priority: 50,
    canDismiss: true
  },
  lab_result: {
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
    textColor: 'text-purple-700',
    badgeColor: 'bg-purple-100 text-purple-800',
    icon: Activity,
    label: 'Résultat labo',
    priority: 60,
    canDismiss: true
  },
  overdue_followup: {
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
    textColor: 'text-orange-700',
    badgeColor: 'bg-orange-100 text-orange-800',
    icon: Clock,
    label: 'Suivi en retard',
    priority: 65,
    canDismiss: true
  },
  success: {
    bgColor: 'bg-green-50',
    borderColor: 'border-green-300',
    textColor: 'text-green-700',
    badgeColor: 'bg-green-100 text-green-800',
    icon: CheckCircle,
    label: 'Succès',
    priority: 30,
    canDismiss: true
  },
  info: {
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
    textColor: 'text-blue-700',
    badgeColor: 'bg-blue-100 text-blue-800',
    icon: Info,
    label: 'Info',
    priority: 20,
    canDismiss: true
  }
};

// Severity configuration for allergies
const SEVERITY_CONFIG = {
  severe: { bg: 'bg-red-600', text: 'text-white', label: 'Sévère' },
  moderate: { bg: 'bg-orange-500', text: 'text-white', label: 'Modéré' },
  mild: { bg: 'bg-yellow-400', text: 'text-gray-900', label: 'Léger' }
};

export default function PatientAlertsBanner({
  patientId,
  alerts = [],
  allergies = [],
  onDismiss,
  onAcknowledge,
  compact = false,
  showAllergies = true,
  maxVisible = 5,
  expandable = true
}) {
  const [isExpanded, setIsExpanded] = useState(true);
  const [showAll, setShowAll] = useState(false);
  const [menuOpen, setMenuOpen] = useState(null);

  // Convert allergies to alert format
  const allergyAlerts = useMemo(() => {
    if (!showAllergies || !allergies?.length) return [];

    return allergies.map((allergy, idx) => ({
      _id: `allergy-${idx}`,
      type: 'allergy',
      sourceType: 'allergy',
      message: allergy.allergen || allergy.name,
      messageFr: `Allergie: ${allergy.allergen || allergy.name}`,
      severity: allergy.severity || 'severe',
      reaction: allergy.reaction,
      autoGenerated: true,
      priority: ALERT_TYPES.allergy.priority + (allergy.severity === 'severe' ? 10 : 0)
    }));
  }, [allergies, showAllergies]);

  // Combine and sort all alerts
  const allAlerts = useMemo(() => {
    const combined = [...allergyAlerts, ...(alerts || [])];

    // Filter out dismissed/expired
    const active = combined.filter(alert => {
      if (alert.dismissedAt) return false;
      if (alert.expiresAt && new Date(alert.expiresAt) < new Date()) return false;
      return true;
    });

    // Sort by priority (highest first)
    return active.sort((a, b) => {
      const priorityA = a.priority || ALERT_TYPES[a.type]?.priority || 0;
      const priorityB = b.priority || ALERT_TYPES[b.type]?.priority || 0;
      return priorityB - priorityA;
    });
  }, [allergyAlerts, alerts]);

  // Visible alerts (respecting maxVisible)
  const visibleAlerts = useMemo(() => {
    if (showAll || !maxVisible) return allAlerts;
    return allAlerts.slice(0, maxVisible);
  }, [allAlerts, showAll, maxVisible]);

  // Count by type
  const alertCounts = useMemo(() => {
    const counts = {};
    allAlerts.forEach(alert => {
      counts[alert.type] = (counts[alert.type] || 0) + 1;
    });
    return counts;
  }, [allAlerts]);

  // Handle dismiss
  const handleDismiss = useCallback(async (alertId) => {
    if (onDismiss) {
      await onDismiss(alertId);
      toast.info('Alerte masquée');
    }
    setMenuOpen(null);
  }, [onDismiss]);

  // Handle acknowledge
  const handleAcknowledge = useCallback(async (alertId) => {
    if (onAcknowledge) {
      await onAcknowledge(alertId);
      toast.success('Alerte prise en compte');
    }
    setMenuOpen(null);
  }, [onAcknowledge]);

  // No alerts
  if (allAlerts.length === 0) {
    return null;
  }

  // Compact mode - just show badges
  if (compact) {
    return (
      <div className="flex flex-wrap gap-2">
        {Object.entries(alertCounts).map(([type, count]) => {
          const config = ALERT_TYPES[type] || ALERT_TYPES.info;
          const Icon = config.icon;
          return (
            <span
              key={type}
              className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium ${config.badgeColor}`}
            >
              <Icon className="w-3 h-3" />
              <span>{count}</span>
            </span>
          );
        })}
      </div>
    );
  }

  // Get the highest priority alert for header color
  const highestPriority = allAlerts[0];
  const headerConfig = ALERT_TYPES[highestPriority?.type] || ALERT_TYPES.info;

  return (
    <div className={`border rounded-lg overflow-hidden bg-white shadow-sm ${headerConfig.borderColor}`}>
      {/* Header */}
      <div
        className={`p-2 flex items-center justify-between ${headerConfig.bgColor} ${expandable ? 'cursor-pointer' : ''}`}
        onClick={() => expandable && setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center gap-3">
          <Bell className={`w-5 h-5 ${headerConfig.textColor}`} />
          <span className={`font-bold ${headerConfig.textColor}`}>
            ALERTES PATIENT
          </span>
          <span className={`px-2 py-0.5 rounded-full text-sm font-medium ${headerConfig.badgeColor}`}>
            {allAlerts.length}
          </span>

          {/* Type badges */}
          <div className="flex gap-1">
            {Object.entries(alertCounts).slice(0, 4).map(([type, count]) => {
              const config = ALERT_TYPES[type] || ALERT_TYPES.info;
              const Icon = config.icon;
              return (
                <span
                  key={type}
                  className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs ${config.badgeColor}`}
                  title={config.label}
                >
                  <Icon className="w-3 h-3" />
                  <span>{count}</span>
                </span>
              );
            })}
          </div>
        </div>

        {expandable && (
          <button className="p-1 hover:bg-black/5 rounded">
            {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
          </button>
        )}
      </div>

      {/* Alerts List */}
      {isExpanded && (
        <div className="divide-y">
          {visibleAlerts.map((alert) => (
            <AlertItem
              key={alert._id}
              alert={alert}
              onDismiss={handleDismiss}
              onAcknowledge={handleAcknowledge}
              menuOpen={menuOpen === alert._id}
              onMenuToggle={() => setMenuOpen(menuOpen === alert._id ? null : alert._id)}
            />
          ))}

          {/* Show More Button */}
          {allAlerts.length > maxVisible && (
            <div className="p-2 flex justify-center bg-gray-50">
              <button
                className="flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900"
                onClick={() => setShowAll(!showAll)}
              >
                {showAll ? 'Voir moins' : `Voir ${allAlerts.length - maxVisible} de plus`}
                {showAll ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * Individual Alert Item
 */
function AlertItem({ alert, onDismiss, onAcknowledge, menuOpen, onMenuToggle }) {
  const config = ALERT_TYPES[alert.type] || ALERT_TYPES.info;
  const Icon = config.icon;
  const canDismiss = config.canDismiss && onDismiss;
  const canAcknowledge = !alert.acknowledgedAt && onAcknowledge;

  return (
    <div
      className={`p-3 flex items-center justify-between ${
        alert.acknowledgedAt ? 'bg-gray-50 opacity-70' : config.bgColor
      }`}
    >
      <div className="flex items-center gap-3 flex-1">
        <Icon className={`w-5 h-5 ${config.textColor}`} />

        <div className="flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`px-2 py-0.5 rounded text-xs font-medium ${config.badgeColor}`}>
              {config.label}
            </span>
            {alert.severity && alert.type === 'allergy' && (
              <span className={`px-2 py-0.5 rounded text-xs font-medium ${SEVERITY_CONFIG[alert.severity]?.bg} ${SEVERITY_CONFIG[alert.severity]?.text}`}>
                {SEVERITY_CONFIG[alert.severity]?.label}
              </span>
            )}
            {alert.autoGenerated && (
              <span className="px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-600 border border-gray-300">
                Auto
              </span>
            )}
          </div>

          <p className="font-medium text-sm mt-1">
            {alert.messageFr || alert.message}
          </p>

          {alert.reaction && (
            <p className="text-xs text-gray-600 mt-0.5">
              Réaction: {alert.reaction}
            </p>
          )}

          {alert.sourceType && alert.sourceType !== 'allergy' && (
            <p className="text-xs text-gray-500">
              Source: {alert.sourceType}
            </p>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2">
        {alert.acknowledgedAt && (
          <span
            className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-600"
            title={`Lu le ${new Date(alert.acknowledgedAt).toLocaleString('fr-FR')}`}
          >
            <Eye className="w-3 h-3" />
            Lu
          </span>
        )}

        {(canDismiss || canAcknowledge) && (
          <div className="relative">
            <button
              className="p-1 hover:bg-black/10 rounded"
              onClick={onMenuToggle}
            >
              <MoreVertical className="w-4 h-4" />
            </button>

            {menuOpen && (
              <div className="absolute right-0 top-full mt-1 bg-white rounded-lg shadow-lg border py-1 z-10 min-w-[150px]">
                {canAcknowledge && (
                  <button
                    className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 flex items-center gap-2"
                    onClick={() => onAcknowledge(alert._id)}
                  >
                    <Eye className="w-4 h-4" />
                    Marquer comme lu
                  </button>
                )}
                {canDismiss && (
                  <button
                    className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 flex items-center gap-2 text-red-600"
                    onClick={() => onDismiss(alert._id)}
                  >
                    <X className="w-4 h-4" />
                    Masquer
                  </button>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Allergy-only banner (for header)
 */
export function AllergyBanner({ allergies = [], compact = false }) {
  if (!allergies?.length) return null;

  // Sort by severity
  const sortedAllergies = [...allergies].sort((a, b) => {
    const order = { severe: 0, moderate: 1, mild: 2 };
    return (order[a.severity] || 2) - (order[b.severity] || 2);
  });

  if (compact) {
    return (
      <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-red-600 text-white">
        <AlertCircle className="w-3 h-3" />
        {allergies.length} Allergie{allergies.length > 1 ? 's' : ''}
      </span>
    );
  }

  return (
    <div className="flex items-start gap-3 p-3 bg-red-50 border-l-4 border-red-500 rounded-md">
      <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
      <div className="flex-1">
        <h4 className="font-bold text-red-700">Allergies</h4>
        <div className="flex flex-wrap gap-2 mt-1">
          {sortedAllergies.map((allergy, idx) => {
            const severityConfig = SEVERITY_CONFIG[allergy.severity] || SEVERITY_CONFIG.severe;
            return (
              <span
                key={idx}
                className={`px-2 py-0.5 rounded text-xs font-medium ${severityConfig.bg} ${severityConfig.text}`}
              >
                {allergy.allergen || allergy.name}
              </span>
            );
          })}
        </div>
      </div>
    </div>
  );
}

/**
 * Single critical alert for inline display
 */
export function CriticalAlertInline({ alert }) {
  if (!alert) return null;

  const config = ALERT_TYPES[alert.type] || ALERT_TYPES.urgent;
  const Icon = config.icon;

  return (
    <div className={`flex items-center gap-2 p-2 rounded-md ${config.bgColor}`}>
      <Icon className={`w-4 h-4 ${config.textColor}`} />
      <span className={`text-sm font-medium ${config.textColor}`}>
        {alert.messageFr || alert.message}
      </span>
    </div>
  );
}

// Export types for external use
export { ALERT_TYPES, SEVERITY_CONFIG };
